server:
  port: 8110 # 服务端口

spring:
  #spring:
  jackson: #返回json的全局时间格式
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  profiles:
    active: dev # 环境设置：会影响logback-spring.xml中配置的日志输出的级别；也会影响nacos配置中心文件
  application:
    name: service-edu # 服务名
  datasource: # mysql数据库连接
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sh0821-guli_edu?serverTimezone=GMT%2B8
    username: root
    password: root
  cloud:
    nacos:
      #nacos注册中心地址
      server-addr: localhost:8848
    sentinel:
      filter:
        url-patterns: /**
      eager: true   #积极加载：项目启动时会自动将本项目注册到sentinel控制台
      transport:
        port: 8081  #本项目和sentinel控制台数据交流时的端口号
        dashboard: localhost:8080   #sentinel控制面板的地址
#MP的日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#设置ribbon远程调用超时时长
ribbon:
  ConnectTimeout: 10000 #连接建立的超时时长，默认1秒
  ReadTimeout: 10000 #处理请求的超时时间，默认为1秒

#openFeign的日志打印级别
logging:
  level:
    com.atguigu.guli.service.edu.feign.OssFeignClient: debug

#启用feign对sentinel的支持
feign:
  sentinel:
    enabled: true
