server:
  port: 8120 # 服务端口

#提取oss的参数
aliyun:
  oss:
    scheme: http://
    endpoint: oss-cn-heyuan.aliyuncs.com
    accessKeyId: LTAI4G9QdS4zyA8HAjAPQ8DM
    accessKeySecret: jrttTMAPrQhwdoMpA8yAmI6FPBLf46
    bucketName: sh0821-onlineedu

spring:
  #spring:
  jackson: #返回json的全局时间格式
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  profiles:
    active: dev # 环境设置：会影响logback-spring.xml中配置的日志输出的级别；也会影响nacos配置中心文件
  application:
    name: service-oss # 服务名

#设置日志输出级别为error：可选fatal（一般不用），error，warning，info（一般测试时用），debug（一般开发时用，可显示参数）
#logging:
#  level:
#    com.atguigu.guli.service.edu.controller.ChapterController: debug
#    root: error
